### ISSUE TITLE
user books property

### ISSUE THREAD

**Issue by natevenn** [adamhundley/the_pivot#2]
as a visitor,                                                                      
when I visit the home page,                                     
and I fill in the city,  check in date, check out date, and number of guest,                                    
and I click on search,                                                  
I expect to see a listing of all properties for that city that are available on those dates,       then I click on a property,                                           
and I expect to see pictures of the property, amenities, price,                                                           
and I click on book,                                                     
then I am redirected to login page,                       
then I fill in with name, email, and password,
and I click on login,
then I am redirected to an order confirmation page,
I expect to see order total, property image,  check in and check out dates, and edit dates,
and I click on confirm order,
then I am prompted to a payment form,
and I fill in payment info,
and I click on submit payment,
then I am redirected to a order summary show page,
I expect to see a link to the property, the order total, check in and check out dates.

**Comment by natevenn** [comment]
as a visitor,                                                                      
when I visit the home page,                                     
and I fill in the city,  check in date, check out date, and number of guest,                                    
and I click on search,                                                  
I expect to see a listing of all properties for that city that are available on those dates,       then I click on a property,                                           
and I expect to see pictures of the property, amenities, price,                                                           
and I click on book,                                                     
then I am redirected to login page,                       
then I fill in with name, email, and password,
and I click on login,
then I am redirected to an order confirmation page,
I expect to see order total, property image,  check in and check out dates, and edit dates,
and I click on confirm order,
then I am prompted to a payment form,
and I fill in payment info,
and I click on submit payment,
then I am redirected to a order summary show page,
I expect to see a link to the property, the order total, check in and check out dates.

**Comment by adamhundley** [comment]
as a visitor,
when I visit the home page,
and I fill in the city,  check in date, check out date, and number of guest,
and I click on search,
I expect to see a listing of all properties for that city that are available on those dates,       then I click on a property,
and I expect to see pictures of the property, amenities, price,
and I click on book,
then I am redirected to login page,
then I fill in with name, email, and password,
and I click on login,
then I am redirected to an order confirmation page,
I expect to see order total, property image,  check in and check out dates, and edit dates,
and I click on confirm order,
then I am prompted to a payment form,
and I fill in payment info,
and I click on submit payment,
then I am redirected to a order summary show page,
I expect to see a link to the property, the order total, check in and check out dates.
